server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: myworkflow
  profiles:
    active: postgres
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  mail:
    host: smtp.example.com
    port: 465
    username: noreply@example.com
    password: change-me

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

flowable:
  database-schema-update: true
  async-executor-activate: true
  check-process-definitions: false
  history-level: full

myworkflow:
  jwt:
    secret: MyWorkflowJwtSecretKeyForApprovalPlatform2026MustBeLongEnough
    expire-hours: 24
  openapi:
    enabled: true
  notify:
    mail-enabled: false
    in-app-enabled: true
  upload-dir: ./data/ticket-files

logging:
  level:
    com.myworkflow: info
    org.flowable: warn

knife4j:
  enable: true
  setting:
    language: zh_cn

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myworkflow;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

---
# 切换：spring.profiles.active=postgres
# 或启动参数 -Dspring-boot.run.profiles=postgres
# 先在 PG 里执行：CREATE DATABASE myworkflow;
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.122:5432/myworkflow
    username: lcms
    password: "3edc#EDC"
