/**
 * bpmn-js 中文词条。key 为 bpmn-js 内部英文原文，不可随意改动。
 */
const zh: Record<string, string> = {
  // 工具栏
  'Activate hand tool': '抓手工具（拖动画布）',
  'Activate the hand tool': '抓手工具（拖动画布）',
  'Activate lasso tool': '框选工具',
  'Activate the lasso tool': '框选工具',
  'Activate create/remove space tool': '空间调整工具',
  'Activate the create/remove space tool': '空间调整工具',
  'Activate global connect tool': '全局连线工具',
  'Activate the global connect tool': '全局连线工具',

  // 调色板
  'Create start event': '开始事件（流程入口）',
  'Create StartEvent': '开始事件（流程入口）',
  'Create end event': '结束事件（流程终点）',
  'Create EndEvent': '结束事件（流程终点）',
  'Create intermediate/boundary event': '中间/边界事件',
  'Create IntermediateThrowEvent/BoundaryEvent': '中间/边界事件',
  'Create gateway': '网关（分支判断）',
  'Create Gateway': '网关（分支判断）',
  'Create task': '任务（改类型为审批节点）',
  'Create Task': '任务（改类型为审批节点）',
  'Create user task': '审批节点（用户任务）',
  'Create UserTask': '审批节点（用户任务）',
  'Create expanded sub-process': '子流程',
  'Create expanded SubProcess': '子流程',
  'Create DataObjectReference': '数据对象',
  'Create data object reference': '数据对象',
  'Create DataStoreReference': '数据存储',
  'Create data store reference': '数据存储',
  'Create pool/participant': '泳池/参与者',
  'Create Pool/Participant': '泳池/参与者',
  'Create group': '分组框',
  'Create Group': '分组框',

  // 右键 / 上下文菜单
  'Append task': '追加任务节点',
  'Append Task': '追加任务节点',
  'Append end event': '追加结束事件',
  'Append EndEvent': '追加结束事件',
  'Append gateway': '追加网关',
  'Append Gateway': '追加网关',
  'Append intermediate/boundary event': '追加中间/边界事件',
  'Append TextAnnotation': '追加文字注释',
  'Append text annotation': '追加文字注释',
  'Add lane above': '在上方添加泳道',
  'Add lane below': '在下方添加泳道',
  'Divide into two lanes': '拆分为两个泳道',
  'Divide into three lanes': '拆分为三个泳道',
  'Change type': '更改节点类型',
  'Change element': '更改节点类型',
  'Connect using sequence/message flow or association': '连线',
  'Connect using Sequence/MessageFlow or Association': '连线',
  'Connect using association': '关联连线',
  'Connect using DataInputAssociation': '数据输入关联',
  'Append user task': '追加审批节点',
  'Append UserTask': '追加审批节点',
  'Append service task': '追加服务任务',
  'Append receive task': '追加接收任务',
  'Append message intermediate catch event': '追加消息中间捕获事件',
  'Append timer intermediate catch event': '追加定时中间捕获事件',
  'Append conditional intermediate catch event': '追加条件中间捕获事件',
  'Append compensation activity': '追加补偿活动',
  'Empty pool': '清空泳池',
  'Empty pool (removes content)': '清空泳池（删除内部内容）',
  'Set color': '设置颜色',
  Remove: '删除',
  Delete: '删除',

  // 弹出菜单（更改类型）的分组标题与搜索框
  Search: '搜索',
  'Search in element types': '搜索节点类型',
  'No results': '没有匹配的类型',
  'No matching entries found': '没有找到匹配项',
  Events: '事件',
  Tasks: '任务',
  Gateways: '网关',
  'Sub-processes': '子流程',
  'Sub Processes': '子流程',
  'Data objects': '数据对象',
  Participants: '参与者',
  Markers: '标记',
  'Loop characteristics': '循环特性',

  // 事件
  'Start event': '开始事件',
  'Start Event': '开始事件',
  'End event': '结束事件',
  'End Event': '结束事件',
  'Intermediate throw event': '中间抛出事件',
  'Intermediate Throw Event': '中间抛出事件',
  'Intermediate catch event': '中间捕获事件',
  'Boundary event': '边界事件',
  'Message start event': '消息开始事件',
  'Timer start event': '定时开始事件',
  'Conditional start event': '条件开始事件',
  'Signal start event': '信号开始事件',
  'Error start event': '错误开始事件',
  'Escalation start event': '升级开始事件',
  'Compensation start event': '补偿开始事件',
  'Message start event (non-interrupting)': '消息开始事件（非中断）',
  'Timer start event (non-interrupting)': '定时开始事件（非中断）',
  'Conditional start event (non-interrupting)': '条件开始事件（非中断）',
  'Signal start event (non-interrupting)': '信号开始事件（非中断）',
  'Escalation start event (non-interrupting)': '升级开始事件（非中断）',
  'Message end event': '消息结束事件',
  'Terminate end event': '终止结束事件',
  'Error end event': '错误结束事件',
  'Escalation end event': '升级结束事件',
  'Cancel end event': '取消结束事件',
  'Compensation end event': '补偿结束事件',
  'Signal end event': '信号结束事件',
  'Link end event': '链接结束事件',
  'Message intermediate catch event': '消息中间捕获事件',
  'Message intermediate throw event': '消息中间抛出事件',
  'Timer intermediate catch event': '定时中间捕获事件',
  'Escalation intermediate throw event': '升级中间抛出事件',
  'Conditional intermediate catch event': '条件中间捕获事件',
  'Link intermediate catch event': '链接中间捕获事件',
  'Link intermediate throw event': '链接中间抛出事件',
  'Compensation intermediate throw event': '补偿中间抛出事件',
  'Signal intermediate catch event': '信号中间捕获事件',
  'Signal intermediate throw event': '信号中间抛出事件',
  'Message boundary event': '消息边界事件',
  'Timer boundary event': '定时边界事件（超时分支）',
  'Escalation boundary event': '升级边界事件',
  'Conditional boundary event': '条件边界事件',
  'Error boundary event': '错误边界事件',
  'Cancel boundary event': '取消边界事件',
  'Signal boundary event': '信号边界事件',
  'Compensation boundary event': '补偿边界事件',
  'Message boundary event (non-interrupting)': '消息边界事件（非中断）',
  'Timer boundary event (non-interrupting)': '定时边界事件（非中断）',
  'Escalation boundary event (non-interrupting)': '升级边界事件（非中断）',
  'Conditional boundary event (non-interrupting)': '条件边界事件（非中断）',
  'Signal boundary event (non-interrupting)': '信号边界事件（非中断）',

  // 任务
  Task: '任务',
  'User task': '审批节点（用户任务）',
  'User Task': '审批节点（用户任务）',
  'Service task': '服务任务（自动执行）',
  'Service Task': '服务任务（自动执行）',
  'Send task': '发送任务',
  'Receive task': '接收任务',
  'Manual task': '手工任务',
  'Business rule task': '业务规则任务',
  'Script task': '脚本任务',
  'Call activity': '调用活动（调用其他流程）',
  'Call Activity': '调用活动（调用其他流程）',
  'Sub process (collapsed)': '子流程（折叠）',
  'Sub process (expanded)': '子流程（展开）',
  'Sub Process (collapsed)': '子流程（折叠）',
  'Sub Process (expanded)': '子流程（展开）',
  'Event sub process': '事件子流程',
  'Event Sub Process': '事件子流程',
  'Transaction sub process': '事务子流程',
  'Ad-hoc sub process': '临时子流程',
  'Ad Hoc Sub Process': '临时子流程',
  Transaction: '事务子流程',

  // 网关
  'Exclusive gateway': '排他网关（只走一条分支）',
  'Exclusive Gateway': '排他网关（只走一条分支）',
  'Parallel gateway': '并行网关（同时走所有分支）',
  'Parallel Gateway': '并行网关（同时走所有分支）',
  'Inclusive gateway': '包容网关（走满足条件的分支）',
  'Inclusive Gateway': '包容网关（走满足条件的分支）',
  'Complex gateway': '复杂网关',
  'Complex Gateway': '复杂网关',
  'Event based gateway': '事件网关',
  'Event based Gateway': '事件网关',
  'Event-based gateway': '事件网关',

  // 连线与标记
  'Sequence flow': '连线',
  'Sequence Flow': '连线',
  'Default flow': '默认分支',
  'Default Flow': '默认分支',
  'Conditional flow': '条件分支',
  'Conditional Flow': '条件分支',
  'Message flow': '消息流',
  Association: '关联',
  'Data association': '数据关联',
  Loop: '循环',
  'Parallel multi instance': '并行多实例（会签）',
  'Parallel Multi Instance': '并行多实例（会签）',
  'Sequential multi instance': '串行多实例（依次审批）',
  'Sequential Multi Instance': '串行多实例（依次审批）',
  'Ad-hoc': '临时',
  Compensation: '补偿',
  'Data object': '数据对象',
  'Data store': '数据存储',
  Pool: '泳池',
  'Participant (expanded)': '参与者（展开）',
  'Participant (collapsed)': '参与者（折叠）',
  Lane: '泳道',
  Group: '分组框',
  'Text annotation': '文字注释',
  'Text Annotation': '文字注释',

  // 提示与错误
  'no parent for {element} in {parent}': '{element} 在 {parent} 中没有父级',
  'no shape type specified': '未指定图形类型',
  'flow elements must be children of pools/participants': '流程元素必须是泳池/参与者的子级',
  'out of bounds release': '超出可放置区域',
  'more than {count} child elements': '子元素超过 {count} 个',
  'element required': '缺少元素',
  'diagram not part of bpmn:Definitions': '图形不属于 bpmn:Definitions',
  'no diagram to display': '没有可显示的流程图',
  'no process or collaboration to display': '没有可显示的流程或协作',
  'element {element} referenced by {referenced}#{property} not yet drawn':
    '{referenced}#{property} 引用的元素 {element} 尚未绘制',
  'already rendered {element}': '{element} 已渲染',
  'failed to import {element}': '导入 {element} 失败',
}

export function createTranslate() {
  return function translate(template: string, replacements?: Record<string, string>) {
    const args = replacements || {}
    const text = zh[template] || template
    return text.replace(/{([^}]+)}/g, (_: string, key: string) =>
      args[key] !== undefined ? String(args[key]) : '{' + key + '}'
    )
  }
}

export const translateModule = {
  translate: ['value', createTranslate()],
}

export default zh
