/** 侧栏和菜单管理共用的内置图标，名称必须与 Element Plus Icons 组件名一致 */
export const MENU_ICONS: { name: string; label: string }[] = [
  { name: 'Menu', label: '菜单' },
  { name: 'Odometer', label: '工作台' },
  { name: 'House', label: '首页' },
  { name: 'Grid', label: '宫格' },
  { name: 'Folder', label: '目录' },
  { name: 'FolderOpened', label: '打开的目录' },
  { name: 'Document', label: '文档' },
  { name: 'Tickets', label: '表单' },
  { name: 'Files', label: '文件' },
  { name: 'Collection', label: '类型' },
  { name: 'List', label: '列表' },
  { name: 'Checked', label: '审批' },
  { name: 'CircleCheck', label: '已办' },
  { name: 'Clock', label: '待办' },
  { name: 'Promotion', label: '发起' },
  { name: 'Share', label: '抄送' },
  { name: 'Plus', label: '新增' },
  { name: 'Edit', label: '编辑' },
  { name: 'Delete', label: '删除' },
  { name: 'Search', label: '搜索' },
  { name: 'SetUp', label: '流程' },
  { name: 'Connection', label: '连线' },
  { name: 'Stamp', label: '印章' },
  { name: 'Setting', label: '设置' },
  { name: 'Tools', label: '工具' },
  { name: 'User', label: '用户' },
  { name: 'UserFilled', label: '实心用户' },
  { name: 'Avatar', label: '角色' },
  { name: 'OfficeBuilding', label: '部门' },
  { name: 'Bell', label: '消息' },
  { name: 'ChatDotRound', label: '会话' },
  { name: 'Notebook', label: '日志' },
  { name: 'DataAnalysis', label: '分析' },
  { name: 'Histogram', label: '柱状图' },
  { name: 'PieChart', label: '饼图' },
  { name: 'Calendar', label: '日历' },
  { name: 'Location', label: '位置' },
  { name: 'Link', label: '链接' },
  { name: 'Lock', label: '锁定' },
  { name: 'Key', label: '密钥' },
  { name: 'Monitor', label: '监控' },
  { name: 'Cpu', label: '系统' },
  { name: 'Box', label: '箱子' },
  { name: 'Goods', label: '物料' },
  { name: 'Van', label: '物流' },
  { name: 'Warning', label: '告警' },
  { name: 'InfoFilled', label: '信息' },
  { name: 'Star', label: '收藏' },
]

export function defaultMenuIcon(menuType?: string) {
  return menuType === 'DIR' ? 'Folder' : 'Document'
}
